In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

#Import dataset
data = pd.read_csv("/Users/hannahkim/Desktop/CSCI Final Project/Dataset.csv", index_col=None, header=0, encoding='latin-1')
data1 = data.drop(['Lizard ID', 'Class 1'], axis=1)
data1.head()

Class 2  Bin #   Bin Length (µm)  Body Weight  Snout to Vent Length  \
0  Hch Mut      51            38.745        0.111                  16.0   
1  Hch Mut      60            38.745        0.111                  16.0   
2  Hch Mut      52            38.745        0.111                  16.0   
3  Hch Mut      53            38.745        0.111                  16.0   
4  Hch Mut      54            38.745        0.111                  16.0   

   Retinal Surface Area  Occular Average (µm)  Macula Diameter  \
0              444328.0                 2068.0            774.9   
1              444328.0                 2068.0            774.9   
2              444328.0                 2068.0            774.9   
3              444328.0                 2068.0            774.9   
4              444328.0                 2068.0            774.9   

   Total Foveal Region length (µm)  GCL  INL  ONL  GCL+INL+ONL  
0                        774.901752   17   79    7          103  
1                        774.901752    7   41    8           56  
2                        774.901752   14   80    8          102  
3                        774.901752   17   65    9           91  
4                        774.901752   14   59    7           80

In [2]:
#Splitting the data into independent and dependent variables
X = data1.iloc[:,1:13].values
y = data1.iloc[:,0].values
print('The independent features set: ')
print(X[:3,:])
print('The dependent variable: ')
print(y[:3])

The independent features set: 
[[5.10000000e+01 3.87450000e+01 1.11000000e-01 1.60000000e+01
  4.44328000e+05 2.06800000e+03 7.74900000e+02 7.74901752e+02
  1.70000000e+01 7.90000000e+01 7.00000000e+00 1.03000000e+02]
 [6.00000000e+01 3.87450000e+01 1.11000000e-01 1.60000000e+01
  4.44328000e+05 2.06800000e+03 7.74900000e+02 7.74901752e+02
  7.00000000e+00 4.10000000e+01 8.00000000e+00 5.60000000e+01]
 [5.20000000e+01 3.87450000e+01 1.11000000e-01 1.60000000e+01
  4.44328000e+05 2.06800000e+03 7.74900000e+02 7.74901752e+02
  1.40000000e+01 8.00000000e+01 8.00000000e+00 1.02000000e+02]]
The dependent variable: 
['Hch Mut' 'Hch Mut' 'Hch Mut']


In [3]:
# Creating the Training and Test set from data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=42)

print(len(X_train))
print(len(X_test))

3692
923


In [4]:
# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors = 5, p=1).fit(X_train, y_train)
knn2 = KNeighborsClassifier(n_neighbors = 5, p=2).fit(X_train, y_train)
knn3 = KNeighborsClassifier(n_neighbors = 5, p=3).fit(X_train, y_train)

In [12]:
accuracy_minowski = knn1.score(X_test, y_test)
accuracy_manhattan = knn2.score(X_test, y_test)
accuracy_euclidean = knn3.score(X_test, y_test)

print(accuracy_minowski)
print(accuracy_manhattan)
print(accuracy_euclidean)

0.9837486457204767
0.9729144095341279
0.962080173347779


In [10]:
knn_predictions = knn.predict(X_test) 
cm = confusion_matrix(y_test, knn_predictions)
print(cm)

[[199   3   0   0   0   0]
 [  2 161   3   2   0   0]
 [  1   1 151   0   0   0]
 [  0   2   1 144   0   0]
 [  0   0   0   0  71   0]
 [  0   0   0   0   0 182]]


In [14]:
from sklearn.metrics import classification_report

print(classification_report(y_test, knn_predictions))

              precision    recall  f1-score   support

      2mo WT       0.99      0.99      0.99       202
      4mo WT       0.96      0.96      0.96       168
      6mo WT       0.97      0.99      0.98       153
      Adt WT       0.99      0.98      0.98       147
     Hch Mut       1.00      1.00      1.00        71
      Hch WT       1.00      1.00      1.00       182

    accuracy                           0.98       923
   macro avg       0.98      0.99      0.98       923
weighted avg       0.98      0.98      0.98       923

